### ISSUE TITLE
Segmentation fault and core dump error.

### ISSUE THREAD

**Issue by NehaPusalkar** [IVLABS/Humanoid-vision#1]
This happens whenever there is no blue colour (colour of the marker) in from of the camera.
Also sometimes when it is unable to detect four corners.

**Comment by anshulpaigwar** [comment]
As I said segmentation faults error occur mostly when you tr to access a memory address that doesn't even exist. So when you got no blue colour and no corners detected there is nothing stored. No memory was allocated for then hence no address exist. But you try to access it you get segmentation fault!

**Comment by aniketgadwe** [comment]
Problem is solved !!

**Comment by anshulpaigwar** [comment]
So you have to mention how you have solved the problem and then close the issue. This is why we are using GitHub so that in future anyone having similar issues can look on to these threads and get his problems solved too.

**Comment by aniketgadwe** [comment]
In my program i was accessing contour.size() greater than zero , but at start there is no blue object in front of camera i.e contour.size is zero. So this gives me segmentation  fault error.
