### ISSUE TITLE
Arena fabrication

### ISSUE THREAD

**Issue by NehaPusalkar** [IVLABS/Humanoid-vision#6]
Complete the fabrication for arena for sprint using green flooring , requires markers and suitable lighting conditions.

**Comment by anshulpaigwar** [comment]
what's the status of arena??

**Comment by NehaPusalkar** [comment]
we will make the humanoid walk on the mat which we have in lab ...and then purchase new green one

**Comment by NehaPusalkar** [comment]
green velvet paper purchased. arena completed
